# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 092de15ed255632a12746d6d9afcf453055886962d4c5c4ddd5f00bba633e67fc5e86c6e7ded3566ed73b81e2deaba989174094da342d9a6517e3bd51c2356de

test:
  secret_key_base: d56a48cb3e6789ab1c4a9ff0047b49abedef45fc1b4a0db530f2b57f99b618f5bef4573553b7220b06dc93701fe1a04be46700150bcecfed9b31e85a4ebebe0c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
